#!/usr/bin/env node

/**
 * Transcription Agent Runner — event-driven, no polling
 *
 * Watches .transcription-trigger via fs.watch (touched by the Python backend
 * whenever a job is ready). On trigger: reads queue, sends to LLM, executes tool.
 *
 * Usage:
 *   node agent-runner/index.js
 *
 * Interactive commands (at the runner> prompt):
 *   status   — Show pending queue items
 *   trigger  — Manually trigger processing
 *   stop     — Shut down
 */

import "dotenv/config";
import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";
import { callModel } from "./model-client.js";
import { executeToolCall } from "./tool-executor.js";
import { logAction } from "./logger.js";
import { readPending, markCleared, acquireLock, releaseLock } from "./poller.js";
import { sanitizeTranscriptSegments, sanitizeContextString } from "./sanitize.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PID_FILE = path.resolve(__dirname, ".runner.pid");
const TRIGGER_FILE = path.resolve(__dirname, "..", "queue", ".transcription-trigger");
const TASK_CHECK_INTERVAL = parseInt(process.env.TASK_CHECK_INTERVAL || "60000", 10);

// ── Tool definitions (self-contained) ──

const TOOLS = [
  {
    name: "transcribe_refine",
    description: "Apply refinement rules to a transcript: redact PII, clean formatting.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        rules: { type: "array", items: { type: "string" } },
      },
      required: ["jobId"],
    },
  },
  {
    name: "transcribe_analyze",
    description:
      "Store LLM-generated analysis of the transcript: topics discussed, sentiment, key entities (names, dates, amounts), meeting effectiveness, and follow-up items.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        analysis: {
          type: "object",
          properties: {
            topics: { type: "array", items: { type: "string" }, description: "List of topics discussed" },
            sentiment: { type: "string", description: "Overall sentiment or per-speaker sentiment summary" },
            key_entities: { type: "array", items: { type: "string" }, description: "Names, dates, amounts, project names mentioned" },
            effectiveness: { type: "string", description: "Meeting effectiveness score/notes" },
            follow_ups: { type: "array", items: { type: "string" }, description: "Questions or items needing future discussion" },
          },
        },
      },
      required: ["jobId"],
    },
  },
  {
    name: "transcribe_get_transcript",
    description: "Get the current speaker-labeled transcript.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        format: { type: "string", enum: ["json", "text"], default: "json" },
      },
      required: ["jobId"],
    },
  },
  {
    name: "transcribe_get_summary",
    description: "Get the meeting summary and action items.",
    inputSchema: { type: "object", properties: { jobId: { type: "string" } }, required: ["jobId"] },
  },
  {
    name: "transcribe_summarize",
    description: "Store a meeting summary generated by the LLM.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        summary: {
          type: "object",
          properties: {
            executive_summary: { type: "string" },
            key_decisions: { type: "array", items: { type: "string" } },
            discussion_points: { type: "array", items: { type: "string" } },
            action_items: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: { type: "string" },
                  assignee: { type: "string" },
                  deadline: { type: "string" },
                },
              },
            },
          },
        },
      },
      required: ["jobId", "summary"],
    },
  },
  {
    name: "transcribe_label_speaker",
    description: "Label an unknown speaker and save their voiceprint.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        speakerId: { type: "string" },
        name: { type: "string" },
        email: { type: "string" },
      },
      required: ["jobId", "speakerId", "name"],
    },
  },
  {
    name: "transcribe_list_voiceprints",
    description: "List all stored voiceprints.",
    inputSchema: { type: "object", properties: {} },
  },
  {
    name: "transcribe_prepare_delivery",
    description: "Prepare deliverable package with transcript + summary.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        destinations: { type: "array", items: { type: "string", enum: ["email", "drive", "trello"] } },
        emailRecipients: { type: "array", items: { type: "string" } },
      },
      required: ["jobId", "destinations"],
    },
  },
  {
    name: "transcribe_search_memory",
    description:
      "Semantic search across past meeting transcripts and summaries using natural language. Returns matching meetings with relevance scores.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Natural language search query, e.g. 'budget discussion Q4'" },
        nResults: { type: "number", default: 5 },
      },
      required: ["query"],
    },
  },
  {
    name: "transcribe_save_ephemeral",
    description: "Save structured data to ephemeral memory: action items, contacts, budgets, decisions, or notes.",
    inputSchema: {
      type: "object",
      properties: {
        table: { type: "string", enum: ["action_items", "contacts", "budgets", "decisions", "notes"] },
        data: {
          type: "object",
          description:
            "Data payload. For action_items: {job_id, items: [{description, assignee, deadline, priority}], meeting_title}. For contacts: {name, email, org, role, phone, meeting}. For budgets: {job_id, items: [{description, amount, currency, category}], meeting_title}. For decisions: {job_id, items: [{description, rationale, made_by}], meeting_title}. For notes: {job_id, topic, content}.",
        },
      },
      required: ["table", "data"],
    },
  },
  {
    name: "transcribe_query_ephemeral",
    description: "Query ephemeral memory for action items, contacts, budgets, decisions, or notes. Optionally filter by keyword.",
    inputSchema: {
      type: "object",
      properties: {
        table: { type: "string", enum: ["action_items", "contacts", "budgets", "decisions", "notes"], default: "notes" },
        query: { type: "string", default: "", description: "Optional keyword to filter results" },
        limit: { type: "number", default: 10 },
      },
      required: [],
    },
  },
  {
    name: "transcribe_save_context",
    description:
      "Save full meeting context to both semantic and ephemeral memory at once. Call this after summarization to make the meeting searchable.",
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        title: { type: "string" },
        attendees: { type: "array", items: { type: "string" } },
        transcriptText: { type: "string", description: "Full transcript as plain text" },
        summary: { type: "object", description: "Summary object with executive_summary, key_decisions, discussion_points" },
        actionItems: { type: "array", items: { type: "object" }, description: "List of {description, assignee, deadline, priority}" },
        budgets: { type: "array", items: { type: "object" }, description: "List of {description, amount, currency, category}" },
        decisions: { type: "array", items: { type: "object" }, description: "List of {description, rationale, made_by}" },
      },
      required: ["jobId", "title"],
    },
  },
  {
    name: "send_delivery_email",
    description: "Send email with meeting summary and transcript via Gmail.",
    inputSchema: {
      type: "object",
      properties: {
        to: { type: "string" },
        subject: { type: "string" },
        body: { type: "string" },
        transcript: { type: "string" },
      },
      required: ["to", "subject", "body"],
    },
  },
  {
    name: "create_trello_action_items",
    description: "Create Trello cards for action items.",
    inputSchema: {
      type: "object",
      properties: {
        listId: { type: "string" },
        actionItems: {
          type: "array",
          items: {
            type: "object",
            properties: {
              description: { type: "string" },
              assignee: { type: "string" },
              deadline: { type: "string" },
            },
          },
        },
      },
      required: ["listId", "actionItems"],
    },
  },
  {
    name: "save_to_drive",
    description: "Save transcript and summary to Google Drive.",
    inputSchema: {
      type: "object",
      properties: {
        folderName: { type: "string" },
        title: { type: "string" },
        transcript: { type: "string" },
        summary: { type: "string" },
      },
      required: ["title"],
    },
  },
];

// ── Processing ──

/**
 * Pipeline state keys — appended to context between LLM calls to
 * guide the LLM toward the next logical step.
 */
const PIPELINE_HINTS = {
  transcribe_refine:
    `Next: Call transcribe_get_transcript to read the refined transcript, ` +
    `then call transcribe_analyze to analyze topics/sentiment/entities, ` +
    `then call transcribe_summarize with a structured summary.`,
  transcribe_get_transcript:
    `Next: Analyze the transcript for topics, sentiment, and key entities, ` + `then call transcribe_analyze to store the analysis results.`,
  transcribe_analyze: `Next: Generate a structured summary from the transcript and analysis, ` + `then call transcribe_summarize to store it.`,
  transcribe_summarize: `Next: Call transcribe_save_context to persist the meeting to semantic + ephemeral memory.`,
  transcribe_save_context: `Next: Call transcribe_prepare_delivery to package results for delivery.`,
  transcribe_prepare_delivery: `Next: Deliver results using send_delivery_email, save_to_drive, or create_trello_action_items.`,
  transcribe_label_speaker: `Next: If more unknown speakers remain, call transcribe_label_speaker again; ` + `otherwise the pipeline is complete.`,
};

/** Terminal tools — once called, the pipeline ends. */
const TERMINAL_TOOLS = new Set(["send_delivery_email", "save_to_drive", "create_trello_action_items"]);

/** Maximum number of LLM rounds per event (safety limit). */
const MAX_PIPELINE_STEPS = 15;

async function processEvent(event) {
  const eventId = event.id;
  const tag = eventId?.slice(0, 8) || "???";

  console.log(`\n   ╔══════════════════════════════════════════╗`);
  console.log(`   ║   🔄 JOB ${tag.padEnd(27)}║`);
  console.log(`   ╚══════════════════════════════════════════╝`);
  console.log(`   📋 ${event.source}/${event.type} — "${event.data?.title || "?"}"`);

  acquireLock(eventId);
  const jobData = event.data || {};
  const rawTranscript = jobData.transcript || [];

  // Sanitize transcript data before building LLM context (Tier 2 — optional)
  const transcript = sanitizeTranscriptSegments(rawTranscript);

  // Sanitize context strings (Tier 2 — optional)
  const safeTitle = sanitizeContextString(jobData.title || "");
  const safeAttendees = (jobData.attendees || []).map((a) => sanitizeContextString(a));

  // Build initial context with job info + transcript preview
  let context = buildInitialContext(event, transcript, safeTitle, safeAttendees, eventId);

  // ── Multi-step pipeline loop ──
  // Each iteration: LLM picks one tool → executes it → result appended to context
  // Loop ends when a terminal tool is called, LLM returns nothing, or max steps hit.
  let pipelineComplete = false;

  for (let step = 1; step <= MAX_PIPELINE_STEPS && !pipelineComplete; step++) {
    console.log(`   🤖 [RUNNER] Asking LLM (step ${step})...`);
    const decision = await callModel(context, TOOLS);

    if (!decision) {
      console.log(`   ⏭️  [RUNNER] No decision — pipeline complete`);
      logAction({ eventId, eventType: event.type, action: "complete", detail: `ended at step ${step}, no LLM decision` });
      pipelineComplete = true;
      break;
    }

    console.log(`   🎯 [RUNNER] ${decision.name}`);
    const result = await executeToolCall(decision.name, decision.arguments);

    // Check for errors (bridge calls return raw JSON, so check for thrown exceptions)
    const ok = result && result.ok !== false;
    const errorMsg = !ok && result?.error ? result.error : null;

    logAction({
      eventId,
      eventType: event.type,
      toolName: decision.name,
      step,
      toolResult: ok ? "success" : "failed",
      error: errorMsg,
    });

    if (!ok) {
      console.log(`   ❌ [RUNNER] ${errorMsg || "Unknown error"}`);
      logAction({ eventId, eventType: event.type, action: "failed", detail: errorMsg });
      pipelineComplete = true;
      break;
    }

    console.log(`   ✅ [RUNNER] ${decision.name} succeeded`);

    // Check if this was a terminal delivery tool — pipeline ends
    if (TERMINAL_TOOLS.has(decision.name)) {
      console.log(`   📬 [RUNNER] Delivery complete — pipeline finished`);
      logAction({ eventId, eventType: event.type, action: "complete", detail: `delivered via ${decision.name}` });
      pipelineComplete = true;
      break;
    }

    // Append result summary to context so the LLM knows what happened
    const resultSummary =
      result && typeof result === "object" && !Array.isArray(result) ? JSON.stringify(result).slice(0, 500) : String(result || "ok").slice(0, 500);
    context += `\n\n[Step ${step} Complete] Tool: ${decision.name}\nResult: ${resultSummary}`;

    // Add a hint about the next logical pipeline step
    const hint = PIPELINE_HINTS[decision.name];
    if (hint) context += `\n${hint}`;
  }

  console.log(`   ✅ [RUNNER] Pipeline finished for job ${tag}`);
  markCleared(eventId);
}

/**
 * Build the initial LLM context for a queue event.
 * Includes job metadata, transcript preview, and pipeline instructions.
 */
function buildInitialContext(event, transcript, safeTitle, safeAttendees, eventId) {
  const jobData = event.data || {};
  const lines = [
    `Transcription job: "${safeTitle}"`,
    `Attendees: ${safeAttendees.join(", ") || "none"}`,
    `Type: ${jobData.eventType || "unknown"}`,
    `Job ID: ${jobData.jobId || eventId}`,
    ``,
  ];

  if (event.type === "ready_for_processing") {
    lines.push("Actions: refine transcript, extract action items, generate summary, prepare delivery.");
    lines.push(`Transcript (${transcript.length} segments):`);
    for (const seg of transcript.slice(0, 10)) {
      lines.push(`  [${seg.start?.toFixed(1)}s] ${seg.speaker}: ${(seg.text || "").slice(0, 100)}`);
    }
    if (transcript.length > 10) lines.push(`  ... (${transcript.length - 10} more)`);
  } else if (event.type === "labeling_needed") {
    lines.push("Unknown speakers detected. List voiceprints, notify user, or apply labels if info available.");
    for (const uk of jobData.unknownSpeakers || []) {
      lines.push(`  - ${uk.speaker_id}: "${(uk.sample_text || "").slice(0, 80)}"`);
    }
  } else if (event.type === "failed") {
    lines.push(`Processing failed. Notify the user. Error: ${jobData.error || "unknown"}`);
  }

  return lines.join("\n");
}

// ── Main loop ──

let isProcessing = false;
let watchTimer = null;

async function mainLoop() {
  if (isProcessing) return;
  isProcessing = true;

  const pending = readPending();
  if (pending.length > 0) {
    console.log(`\n   🔔 [RUNNER] ${pending.length} pending job(s)`);
    await processEvent(pending[0]);
  }

  isProcessing = false;
}

// ── Startup ──

const provider = process.env.LLM_PROVIDER || "deepseek";
const model = provider === "ollama" ? process.env.OLLAMA_MODEL || "llama3.1:8b" : "deepseek-v4-flash";
console.log(`\n${"─".repeat(50)}`);
console.log(`   🎙️  Transcription Agent Runner`);
console.log(`   🤖 ${provider} (${model})`);
console.log(`   🔄 fs.watch on .transcription-trigger (push-based)`);
console.log(`   🛠️  ${TOOLS.length} tools`);
console.log(`${"─".repeat(50)}\n`);

fs.writeFileSync(PID_FILE, String(process.pid));

// Ensure trigger file exists
try {
  if (!fs.existsSync(TRIGGER_FILE)) fs.writeFileSync(TRIGGER_FILE, "");
} catch {
  /* */
}

// Watch for trigger
const watcher = fs.watch(TRIGGER_FILE, () => {
  if (watchTimer) clearTimeout(watchTimer);
  watchTimer = setTimeout(() => mainLoop(), 100);
});

// Fallback timer
let taskTimer = null;
if (TASK_CHECK_INTERVAL > 0) taskTimer = setInterval(mainLoop, TASK_CHECK_INTERVAL);

// Run once on startup
mainLoop();

// ── Interactive terminal ──

const rl = readline.createInterface({ input: process.stdin, output: process.stdout, prompt: "runner> ", terminal: true });
rl.prompt();

rl.on("line", (input) => {
  const cmd = input.trim().toLowerCase();
  if (["stop", "exit", "quit"].includes(cmd)) {
    console.log("   👋 Shutting down...");
    watcher.close();
    if (taskTimer) clearInterval(taskTimer);
    rl.close();
    process.exit(0);
  } else if (cmd === "status") {
    const items = readPending();
    console.log(`   📋 Queue: ${items.length} pending`);
    for (const item of items) console.log(`      ${item.id?.slice(0, 8)} ${item.source}/${item.type} — "${item.data?.title || "?"}"`);
    rl.prompt();
  } else if (cmd === "trigger") {
    try {
      fs.utimesSync(TRIGGER_FILE, new Date(), new Date());
      console.log("   🔔 Triggered");
    } catch {
      console.log("   ❌ Failed");
    }
    rl.prompt();
  } else if (cmd === "help") {
    console.log("   stop/exit/quit  — Shut down");
    console.log("   status — Show queue");
    console.log("   trigger — Manually trigger");
    rl.prompt();
  } else {
    rl.prompt();
  }
});

rl.on("close", () => process.exit(0));
