/**
 * License Manager — per-seat Ed25519 license verification + local persistence.
 *
 * Trust model:
 *   MASTER keypair (maintainer, offline) signs each seat CERT:
 *     cert = { app, v, sub, exp, kid, pub }   (pub = seat's public key)
 *   License key string (what the user enters / is issued):
 *     TA1.<b64url(certJson)>.<b64url(masterSig)>.<b64url(seatPrivRaw)>
 *
 * Verification (fully offline):
 *   1. Resolve the master public key from MASTER_KEY_RING by cert.kid.
 *      Reject unknown kid, revoked kid (REVOKED_KIDS), or retired past notAfter.
 *   2. Verify the master signature over the cert bytes.
 *   3. Prove the holder possesses the matching seat private key
 *      (derive public key from seat private key; must equal cert.pub).
 *   4. Check app/v and exp (exp = 0 means UNLIMITED).
 *
 * Persistence (userData/):
 *   license.json    — NON-secret metadata: { status, sub, kid, exp, installedAt }
 *   license.key.enc — the raw license key, encrypted via Electron safeStorage
 *                     (Keychain on macOS, DPAPI on Windows).
 *
 * There is deliberately NO plaintext fallback: if safeStorage is unavailable
 * the license simply cannot be persisted (activation reports no_secure_storage)
 * and the config stays unencrypted. The license key is never written to disk
 * in the clear.
 *
 * The MASTER key ring is version-independent: normal app updates keep the same
 * ring (or extend it) so existing license keys keep working. Rotation/revocation
 * is rare (compromise / deliberate policy) — see the ring's notAfter + REVOKED_KIDS.
 */
import { app, safeStorage } from "electron";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import { addLog } from "./logger";

export const APP_ID = "transcription-agent";
export const LICENSE_VERSION = 1;
export const LICENSE_KEY_RE = /^TA1\.([A-Za-z0-9_-]+)\.([A-Za-z0-9_-]+)\.([A-Za-z0-9_-]+)$/;

export interface MasterKeyEntry {
  kid: string;
  /** base64url raw 32-byte Ed25519 public key */
  publicKey: string;
  /** unix seconds after which keys signed by this master are retired; null/absent = valid forever */
  notAfter?: number | null;
}

/**
 * Embedded master public key ring.
 *
 * Dev key is generated by scripts/license.mjs (dev-keys/, gitignored — private
 * key never committed). Replace with the real ring before release; keep retired
 * masters here with a notAfter date for a grace period, or remove them entirely
 * and add their kid to REVOKED_KIDS on compromise.
 */
export const MASTER_KEY_RING: MasterKeyEntry[] = [{ kid: "mk-dev", publicKey: "nHwVcrYKtcXv5SokVALtbhPcWR-ZgdmphKEPeAjDXnI", notAfter: null }];

/** kids whose signatures are no longer trusted (compromise / forced retirement). */
export const REVOKED_KIDS: string[] = [];
/** Per-seat revocation — a specific seat (sub) is invalidated without retiring its master kid. */
export const REVOKED_SEATS: string[] = ["lic_test@test.com"];

export interface LicenseClaims {
  app: string;
  v: number;
  sub: string;
  exp: number; // 0 = unlimited
  kid: string;
  pub: string;
}

export type VerifyResult =
  | { ok: true; claims: LicenseClaims }
  | {
      ok: false;
      reason:
        | "malformed"
        | "malformed_cert"
        | "app_mismatch"
        | "unknown_kid"
        | "revoked_kid"
        | "revoked_seat"
        | "retired_kid"
        | "bad_signature"
        | "bad_seat_key"
        | "key_mismatch"
        | "expired";
    };

export type LicenseStatus =
  | { status: "unlicensed" }
  | { status: "active"; sub: string; kid: string; exp: number; installedAt?: number }
  | { status: "expired"; sub: string; kid: string; exp: number; installedAt?: number }
  | { status: "invalid"; reason: string };

// ── Verification ──────────────────────────────────────────────────────────────

function ringEntryFor(kid: string): MasterKeyEntry | undefined {
  return MASTER_KEY_RING.find((k) => k.kid === kid);
}

/**
 * Verify a license key string. Pure — no disk/Electron side effects.
 * `nowMs` injectable for tests.
 */
export function verifyLicenseKey(licenseKey: string, nowMs: number = Date.now()): VerifyResult {
  const m = LICENSE_KEY_RE.exec(licenseKey);
  if (!m) return { ok: false, reason: "malformed" };
  const [, certB64, sigB64, seatPrivB64] = m;

  let cert: LicenseClaims;
  try {
    cert = JSON.parse(Buffer.from(certB64, "base64url").toString("utf8"));
  } catch {
    return { ok: false, reason: "malformed_cert" };
  }
  if (cert.app !== APP_ID || cert.v !== LICENSE_VERSION) return { ok: false, reason: "app_mismatch" };

  const entry = ringEntryFor(cert.kid);
  if (!entry) return { ok: false, reason: "unknown_kid" };
  if (REVOKED_KIDS.includes(cert.kid)) return { ok: false, reason: "revoked_kid" };
  if (entry.notAfter && nowMs >= entry.notAfter * 1000) return { ok: false, reason: "retired_kid" };
  if (REVOKED_SEATS.includes(cert.sub)) return { ok: false, reason: "revoked_seat" };

  const masterPub = crypto.createPublicKey({ key: { kty: "OKP", crv: "Ed25519", x: entry.publicKey }, format: "jwk" });
  const certBytes = Buffer.from(certB64, "base64url");
  if (!crypto.verify(null, certBytes, masterPub, Buffer.from(sigB64, "base64url"))) {
    return { ok: false, reason: "bad_signature" };
  }

  // Seat possession: the private key embedded in the license must match cert.pub.
  let derivedPub: string;
  try {
    const seatPriv = crypto.createPrivateKey({ key: { kty: "OKP", crv: "Ed25519", x: cert.pub, d: seatPrivB64 }, format: "jwk" });
    const jwk = seatPriv.export({ format: "jwk" }) as { x?: string };
    if (!jwk.x) return { ok: false, reason: "bad_seat_key" };
    derivedPub = jwk.x;
  } catch {
    return { ok: false, reason: "bad_seat_key" };
  }
  if (derivedPub !== cert.pub) return { ok: false, reason: "key_mismatch" };

  if (cert.exp !== 0 && nowMs >= cert.exp * 1000) return { ok: false, reason: "expired" };

  return { ok: true, claims: cert };
}

// ── Persistence ───────────────────────────────────────────────────────────────

const LICENSE_DIR_NAME = "license";

function licenseDir(): string {
  return path.join(app.getPath("userData"), LICENSE_DIR_NAME);
}
function licenseJsonPath(): string {
  return path.join(licenseDir(), "license.json");
}
function licenseKeyEncPath(): string {
  return path.join(licenseDir(), "license.key.enc");
}

// Legacy locations (pre-0.9): license files lived in the userData root. A
// one-time migration moves them into userData/license/ on first read/write.
function legacyLicenseJsonPath(): string {
  return path.join(app.getPath("userData"), "license.json");
}
function legacyLicenseKeyEncPath(): string {
  return path.join(app.getPath("userData"), "license.key.enc");
}

function ensureLicenseDir(): void {
  fs.mkdirSync(licenseDir(), { recursive: true });
}

function migrateLegacyLicenseFiles(): void {
  try {
    ensureLicenseDir();
    if (!fs.existsSync(licenseJsonPath()) && fs.existsSync(legacyLicenseJsonPath())) {
      fs.renameSync(legacyLicenseJsonPath(), licenseJsonPath());
    }
    if (!fs.existsSync(licenseKeyEncPath()) && fs.existsSync(legacyLicenseKeyEncPath())) {
      fs.renameSync(legacyLicenseKeyEncPath(), licenseKeyEncPath());
    }
  } catch {
    // non-fatal
  }
}

interface LicenseJson {
  status?: string;
  sub?: string;
  kid?: string;
  exp?: number;
  installedAt?: number;
}

function readLicenseJson(): LicenseJson {
  try {
    migrateLegacyLicenseFiles();
    const raw = fs.readFileSync(licenseJsonPath(), "utf8");
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

function writeLicenseJson(data: LicenseJson): void {
  try {
    ensureLicenseDir();
    fs.writeFileSync(licenseJsonPath(), JSON.stringify(data, null, 2), "utf8");
    try {
      if (fs.existsSync(legacyLicenseJsonPath())) fs.unlinkSync(legacyLicenseJsonPath());
    } catch {
      // ignore
    }
  } catch {
    // Non-fatal
  }
}

/** Read the raw license key back from storage. Returns null if none stored. */
export function readStoredLicenseKey(): string | null {
  // The license key is only ever persisted via OS secure storage. There is NO
  // plaintext fallback: if safeStorage is unavailable the key is not persisted.
  if (!safeStorage.isEncryptionAvailable()) return null;
  try {
    migrateLegacyLicenseFiles();
    if (fs.existsSync(licenseKeyEncPath())) {
      const buf = fs.readFileSync(licenseKeyEncPath());
      return safeStorage.decryptString(buf);
    }
    return null;
  } catch {
    return null;
  }
}

/** Store (or clear, when key is null) the raw license key. */
export function writeStoredLicenseKey(key: string | null): void {
  ensureLicenseDir();
  const encPath = licenseKeyEncPath();
  if (key === null) {
    try {
      if (fs.existsSync(encPath)) fs.unlinkSync(encPath);
    } catch {
      // ignore
    }
    const json = readLicenseJson();
    writeLicenseJson(json);
    try {
      if (fs.existsSync(legacyLicenseKeyEncPath())) fs.unlinkSync(legacyLicenseKeyEncPath());
    } catch {
      // ignore
    }
    return;
  }

  // Only ever persisted via safeStorage — never a plaintext fallback.
  if (!safeStorage.isEncryptionAvailable()) return;
  fs.writeFileSync(encPath, safeStorage.encryptString(key));
  const json = readLicenseJson();
  writeLicenseJson(json);
  try {
    if (fs.existsSync(legacyLicenseKeyEncPath())) fs.unlinkSync(legacyLicenseKeyEncPath());
  } catch {
    // ignore
  }
}

// ── Censored license-flow logging ──────────────────────────────────────────────
// Every license event is written to BOTH the live log (DevPanel, via addLog,
// subSource "license") and a dedicated append-only userData/license.log (JSON
// lines). NEVER pass the raw license key, seat private key, cert, sig, bridge
// token, or any decrypted secret into these helpers — only safe fields
// (sub, kid, exp, status, reason…).

const LICENSE_LOG_NAME = "license.log";
const LICENSE_LOG_DIR_NAME = "logs";
const LICENSE_LOG_MAX_BYTES = 2 * 1024 * 1024;

function licenseLogPath(): string {
  return path.join(app.getPath("userData"), LICENSE_LOG_DIR_NAME, LICENSE_LOG_NAME);
}

/**
 * Emit a censored license-flow event to the live log + userData/license.log.
 * `fields` must only contain non-sensitive values.
 */
export function logLicenseFlow(level: "info" | "warn" | "error", event: string, fields: Record<string, unknown> = {}): void {
  const ts = new Date().toISOString();
  try {
    const p = licenseLogPath();
    fs.mkdirSync(path.dirname(p), { recursive: true });
    if (fs.existsSync(p) && fs.statSync(p).size > LICENSE_LOG_MAX_BYTES) {
      try {
        fs.renameSync(p, `${p}.1`); // rotate: keep one previous file
      } catch {
        // ignore
      }
    }
    fs.appendFileSync(p, JSON.stringify({ ts, level, event, ...fields }) + "\n", "utf8");
  } catch {
    // non-fatal
  }
  const summary = Object.entries(fields)
    .map(([k, v]) => `${k}=${String(v)}`)
    .join(" ");
  addLog("main", level, `[license] ${event}${summary ? ` — ${summary}` : ""}`, "license");
}

/** Log the current runtime license status once (e.g. at app startup). */
export function logCurrentLicenseStatus(): void {
  const payload = getLicenseStatusPayload();
  const s = payload.status;
  if (s.status === "active") logLicenseFlow("info", "status", { status: "active", sub: s.sub, kid: s.kid, exp: s.exp });
  else if (s.status === "expired") logLicenseFlow("warn", "status", { status: "expired", sub: s.sub, kid: s.kid, exp: s.exp });
  else if (s.status === "invalid") logLicenseFlow("warn", "status", { status: "invalid", reason: s.reason });
  else logLicenseFlow("info", "status", { status: "unlicensed" });
}

// ── Status / lifecycle ────────────────────────────────────────────────────────

export function isLicensed(): boolean {
  return readStoredLicenseKey() !== null;
}

/** Current runtime license status (re-verifies the stored key each call). */
export function getLicenseStatus(): LicenseStatus {
  const key = readStoredLicenseKey();
  const json = readLicenseJson();
  if (!key) return { status: "unlicensed" };

  const res = verifyLicenseKey(key);
  if (res.ok) {
    return {
      status: "active",
      sub: res.claims.sub,
      kid: res.claims.kid,
      exp: res.claims.exp,
      installedAt: json.installedAt,
    };
  }
  if (res.reason === "expired") {
    return { status: "expired", sub: json.sub || "", kid: json.kid || "", exp: json.exp || 0, installedAt: json.installedAt };
  }
  return { status: "invalid", reason: res.reason };
}

/**
 * Activate a license key. On success persists the key (safeStorage) + metadata.
 * Also returns whether the key was stored via the plaintext fallback.
 */
export function activateLicense(key: string): {
  ok: boolean;
  reason?: string;
  status?: LicenseStatus;
} {
  logLicenseFlow("info", "activation.requested");
  const res = verifyLicenseKey(key);
  if (!res.ok) {
    logLicenseFlow("warn", "activation.failed", { reason: res.reason });
    return { ok: false, reason: res.reason };
  }

  // Require OS secure storage: the license key is a bearer credential and must
  // never be persisted in plaintext on disk.
  if (!safeStorage.isEncryptionAvailable()) {
    logLicenseFlow("warn", "activation.failed", { reason: "no_secure_storage" });
    return { ok: false, reason: "no_secure_storage" };
  }

  writeStoredLicenseKey(key);
  const json: LicenseJson = {
    status: "active",
    sub: res.claims.sub,
    kid: res.claims.kid,
    exp: res.claims.exp,
    installedAt: Date.now(),
  };
  writeLicenseJson(json);

  logLicenseFlow("info", "activated", {
    sub: res.claims.sub,
    kid: res.claims.kid,
    exp: res.claims.exp,
  });
  return { ok: true, status: getLicenseStatus() };
}

/** Remove the license (back to unlicensed). Does NOT touch the encrypted config. */
export function deactivateLicense(): { ok: boolean } {
  writeStoredLicenseKey(null);
  writeLicenseJson({ status: "unlicensed" });
  logLicenseFlow("info", "deactivated");
  return { ok: true };
}

/** Full status payload for the renderer. */
export function getLicenseStatusPayload(): { status: LicenseStatus; safeStorageAvailable: boolean } {
  return { status: getLicenseStatus(), safeStorageAvailable: safeStorage.isEncryptionAvailable() };
}

/** Whether the raw license key file is present on disk (recovery UI). */
export function getLicenseKeyFileStatus(): "present" | "missing" {
  if (!safeStorage.isEncryptionAvailable()) return "missing";
  return fs.existsSync(licenseKeyEncPath()) ? "present" : "missing";
}
